# This file's format is documented at
# https://forge.rust-lang.org/triagebot/pr-assignment.html#configuration

[relabel]
allow-unauthenticated = [
    "A-*",
    "C-*",
]

#[relabel.to-stable]
#add-labels = ["regression-from-stable-to-stable"]
#rem-labels = ["regression-from-stable-to-beta", "regression-from-stable-to-nightly"]

[relabel.to-beta]
add-labels = ["regression-from-stable-to-beta"]
rem-labels = ["regression-from-stable-to-stable", "regression-from-stable-to-nightly"]
